name: Run_Suites_testresults
run-name: "Ghost Inspector: ${{ github.actor }} triggered on-demand test"

on:
  workflow_dispatch:
    inputs:
      collection:
        description: 'Select Suite to run'
        required: true
        type: choice
        options:
          - TestLab1
          - TestLab2
      build_version:
        description: 'Build Version(xx.xx.xxx.xxxx)'
        required: true
        type: string
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-gi-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Newman
        run: npm install -g newman

      - name: Run Selected Collection
        run: |
          case "${{ inputs.collection }}" in
            TestLab1)
              newman run Execution/Amita_TestLab1.postman_collection.json \
                -e Variables/6.0_Postman_variables \
                --env-var "tmsBuildVersion=${{ inputs.build_version }}" \
                --reporters cli
              ;;
            TestLab2)
                  newman run Execution/Amita_TestLab22.postman_collection.json \
                    -e Variables/6.0_Postman_variables \
                    --env-var "tmsBuildVersion=${{ inputs.build_version }}" \
                    --reporters cli
              ;;
          esac
